name: combatlogNB
main: me.clonalejandro.combatlogNB.Main
version: 2.0 Release
author: clonalejandro
description: A combatlog plugin for Noobsters
website: https://clonalejandro.me
commands:
  combatlog:
    usage: /<command>
    description: return info of this plugin